SpbAU, 302, Software Design, Olga Chernikova, task01-CLI
olga24912/term5-software-design pull request #1
Opened 2016-09-11 20:14 UTC by olga24912

2016-09-18 20:50 UTC, yurii-litvinov commented on cli/src/main/java/Assignment.java
> -import java.io.InputStream;
радикальный "фикс" :)

2016-09-18 20:51 UTC, yurii-litvinov commented on cli/src/main/java/Assignment.java
> -import java.io.InputStream;
кстати, комментарий к коммиту "fix", не очень, надо подробнее писать, что и зачем поменялось

2016-09-19 14:24 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Assignment.java
> +    // var - name of variable, data - new value (var=data)
комментарии к методам тоже надо бы в JavaDoc-формате, а то они не попадут в документацию

2016-09-19 14:25 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Assignment.java
> +    // put in environment new value
более по-английски, кстати, было бы "put new value into environment"

2016-09-19 14:26 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/CatCommand.java
> + * Class for command cat
И тут, "Class for 'cat' command". Я, конечно, не эксперт по английскому, но вы сами меня просили комментить :)

2016-09-19 14:28 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/CatCommand.java
> +                FileInputStream fileInputStream = new FileInputStream(fileName);
мне кажется, поток не закрывается нигде

2016-09-19 14:30 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Command.java
> + */
короткие комментарии допустимо писать в одну строчку, чтобы не загромождать код:

    /** abstract class for all commands (like echo, pwd, wc, ..., NOT for: =, |) */

2016-09-19 14:32 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Command.java
> +    public ArrayList<String> getArgs() {
с архитектурной точки зрения плохо, нарушает инкапсуляцию и вызывает недоумение у пользователя --- как ему лучше сделать, argSize() или getArgs().size()

2016-09-19 14:33 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Command.java
> +    public ArrayList<String> getArgs() {
иногда стайлгайды вообще запрещают возвращать мутабельные коллекции, но я не настолько радикален, поэтому иногда можно

2016-09-19 15:14 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Environment.java
> +public class Environment {
кстати, а зачем все классы public? и разбиение по пакетам имело бы смысл сделать более "мелкозернистым", например, сложить все команы в отдельный пакет. декомпозиция и всё такое :)

2016-09-19 15:14 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Environment.java
> +        StringBuilder  result = new StringBuilder();
а тут пробел лишний^U

2016-09-19 15:15 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/ExecutionResult.java
> +public class ExecutionResult {
комментариев не хватает

2016-09-19 15:16 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Lexer.java
> + * Class that parse string to tokens.
Class that parse**s**

2016-09-19 15:21 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Lexer.java
> +
пустые строки перед } обычно не ставятся

2016-09-19 15:26 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Lexer.java
> +}
какая-то суровая смесь лексера и рекурсивного спуска. я подозреваю, что можно было бы проще через регэкспы, но не берусь написать код, чтобы показать, как :)

2016-09-19 15:27 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Main.java
> +        while(!finishFlag) {
пробела не хватает: while (!finishFlag)

2016-09-19 15:28 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Parser.java
> +    int position;
а зачем этим полям пакетная видимость?

2016-09-19 15:28 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Parser.java
> +        }
о, фабрика команд, лучше её в отдельный метод

2016-09-19 15:29 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/PipeCommand.java
> +    Statement right;
тоже пакетная видимость, а раз у Вас один пакет, то это фактически public-поля

2016-09-19 15:31 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Token.java
> +        if (o == null || getClass() != o.getClass()) return false;
лучше 
```java
if (this == o) {
    return true;
}
```
и в подобных местах тоже. В одну строчку обычно допускается, но с фигурными скобками обычно рекомендуется

2016-09-19 15:32 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Token.java
> +
лишняя пустая строка :)

2016-09-19 15:33 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Token.java
> +
и тут

2016-09-19 15:33 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/UnknownCommand.java
> +    String name;
ещё одно package-поле

2016-09-19 15:34 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/WcCommand.java
> +        int cntLine = 0, cntWord = 0, cntBytes = 0;
лучше все объявления на отдельных строчках

2016-09-19 15:34 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/WcCommand.java
> +                FileInputStream fileInputStream = new FileInputStream(fileName);
тоже, кажется, никто не закрывает поток

2016-09-19 15:35 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/package-info.java
> + **/
тут надо ещё package ru.spbau.mit; под комментарием

2016-09-19 15:35 UTC, yurii-litvinov commented on cli/src/test/java/TestCommon.java
> +            assertFalse(true);
есть же fail()

2016-09-19 15:36 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/CommandLine.java
> + * interface for all type of command include pipe and assign.
Английский: interface for all type of command, including pipe and assign

2016-09-19 15:36 UTC, yurii-litvinov commented on cli/src/test/java/TestCommon.java
> +            assertFalse(true);
но даже если бы его не было, то зачем ловить исключение? его поймает jUnit и сам пометит тест как проваленный

2016-09-19 15:38 UTC, yurii-litvinov requested changes
ещё хочется диаграмму с классами

2016-09-19 15:38 UTC, yurii-litvinov commented on cli/src/test/java/TestCommon.java
> +        assertFalse(executionResult == null);
assertNotNull :)

2016-09-25 17:26 UTC, olga24912 commented
@yurii-litvinov здесь я, вроде, все поправила.

2016-10-18 08:21 UTC, yurii-litvinov requested changes
Доисправляйте, пожалуйста.

2016-10-18 08:21 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Command/Assignment.java
> +     * @param var - name of variable
JavaDoc сам генерирует дефис, так что дефис между именем параметра и описанием не ставится

2016-10-18 08:21 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Command/CatCommand.java
> + * write concatenation content of files,
Как-то не по-английски. Writes concatenation of contents of the files?

2016-10-18 08:21 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Command/CommandLine.java
> +/** interface for all type of command, including pipe and assign */
for all type**s**

2016-10-18 08:21 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Command/CommandLine.java
> +     * @param environment info about variable in fact use only in assignment
Тоже как-то не по-английски. "info about variable. In fact, it is used only in assignment"?

2016-10-18 08:21 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Command/CommandLine.java
> +     * @throws IOException
Для исключений тоже надо писать комментарии, описывающие ситуации, в которых они бросаются.

2016-10-18 08:21 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Command/GrepCommand.java
> +                    }
И full word, и case insensitive можно было реализовать самими регулярными выражениями, например, через Pattern.CASE_INSENSITIVE или флаг ?i в самом регэкспе. Слова целиком ищутся через шаблон \b.

2016-10-18 08:21 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Parser.java
> +        while(position < tokens.size() && currentToken().getType() != TokenType.TokenPipe) {
Тут пробела перед "(" не хватает.

2016-10-18 08:21 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/ParsingException.java
> +public class ParsingException extends Throwable {
Этой штуке тоже неплохо бы комментарий.

2016-10-18 08:21 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/TokenType.java
> +public enum TokenType {
И тут, комментария не хватает.

2016-10-18 08:21 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/Utils.java
> +    public static InputStream fromStringToInputStream (String s) {
И тут, комментарий

2016-10-18 08:21 UTC, yurii-litvinov commented on cli/src/test/java/TestCommon.java
> +            fail();
В тестах обычно вообще не пишут try-catch блоки, тест throws Exception, и если оно бросается, его ловит сама среда юнит-тестирования и помечает тест как проваленный. Делать это вручную не нужно.

2016-10-18 08:21 UTC, yurii-litvinov commented on cli/src/test/java/TestCommon.java
> +            fail();
Лучше вместо if-а сделать assertNotNull, всё равно если условие assert-а не выполнено, тест будет прерван.

2016-10-18 08:21 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/package-info.java
> + **/
Вообще, я обратил внимание, что у Вас много проблем с согласованием в английских текстах. Читается в духе "моя твоя башка дубина бить" :) Например, не "contain", а "contains".

2016-11-30 10:25 UTC, yurii-litvinov approved these changes

2016-11-30 10:25 UTC, yurii-litvinov commented on cli/src/test/java/TestCommon.java
> +            fail();
ммм...

2016-11-30 10:25 UTC, yurii-litvinov commented on cli/src/test/java/TestEnvironment.java
> +            assertFalse(true);
- ловить исключения тут вроде незачем
- тут fail() смотрелся бы лучше

2016-11-30 10:25 UTC, merged